# Generated by Django 5.2.6 on 2025-09-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
