# Generated by Django 5.2.6 on 2025-09-27 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0002_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('starred', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mails', to='CleanixDb.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mails', to='CleanixDb.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='mail_attachments/')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='CleanixDb.mail')),
            ],
        ),
    ]
