# Generated by Django 5.2.6 on 2025-09-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0003_mail_filestorage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
