# Generated by Django 5.2.6 on 2025-09-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0004_rename_message_id_filestorage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
