# Generated by Django 5.2.6 on 2025-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0005_mail_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='permanent_delete',
            field=models.BooleanField(default=False),
        ),
    ]
