# Generated by Django 5.2.6 on 2025-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0006_mail_permanent_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
