# Generated by Django 5.2.6 on 2025-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0007_mail_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
