# Generated by Django 5.2.6 on 2025-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CleanixDb', '0009_user_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.CharField(default='cleanixserver@gmail.com')),
                ('public_key', models.BigIntegerField(default=5)),
                ('private_key', models.BigIntegerField(default=54461)),
                ('N', models.BigIntegerField(default=136891)),
            ],
        ),
    ]
